title: Adebambo Olalekan Babatunde
logo: image.jpg
description: A Data Analyst with about one year experience in Report Automation using Advanced Excel, Data Manipulation and Interrogation on Structured Query Language and Business Intelligence Report on Power BI.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
